export const globalMessage = {
  errorMessage: "Something went wrong, Please try again later",
  recordsFound: "Records found",
  recordsNotFound: "Records not found",
  recordsNotFoundToUpdate: "Records not found to update",
  createSuccess: "Created susscessfully.",
  createError: "Error while creating",
  invalidToken: "Invalid Token, please enter valid token",
  userIdRequired: "UserId is required",
  noToken: "No token provided, Please provide token",
};
export const alertMessage = {
  users: {
    createSuccess: "User saved successfully",
    createError: "Error while creating user, Please try again later",
    updateSuccess: "User updated successfully",
    updateError: "Error while updating user, Please try again later",
    deleteSuccess: "User deleted successfully",
    deleteError: "Error while deleting user, please try again later",
    listSuccess: "User record(s) found successfully",
    listError: "User record(s) not found, please try again later",
    internalError: "Internal error",
    loginSuccess: "Login successfully",
    loginError: "Email / mobile number or password is incorrect, please try again",
    logoutSuccess: "Logout successfully",
    logoutError: "Error while logout, please try again",
    invalidPassword: "Sorry, your password is incorrect, please try again",
    noUserDataFound: "User not found",
    passwordChangeSuccess: "Password changed successfully",
    passwordMismatched: "password mismatched, please enter correct password",
    otpVerified: "Otp verified",
    invalidOTP: "Invalid Otp",
    otpNotVerified: "Otp not verified, verify it first",
    notEmptyOTP: "Enter Otp",
    otpSend: "Otp sent to your mobile number",
    otpSendToEmail: "Otp sent to your registered email",
    notEmptyMobile: "Mobile should not empty",
    userAlreadyExistsMobile: "User already exist with given mobile number",
    userAlreadyExistsEmail: "User already exist with given email",
    inActiveAccount: "Your account is deactivated by admin",
    blockUser: "This user is block, Please contact to admin",
    signUpSuccess: " Sign up successful",
  },
  role : {
    createSuccess: "role saved successfully",
    createError: "Error while creating role, Please try again later",
    updateSuccess: "role updated successfully",
    updateError: "Error while updating role, Please try again later",
    deleteSuccess: "role deleted successfully",
    deleteError: "Error while deleting role, please try again later",
    listSuccess: "role record(s) found successfully",
    listError: "role record(s) not found, please try again later",
  },
  Item : {
    createSuccess: "Item saved successfully",
    createError: "Error while creating Item, Please try again later",
    updateSuccess: "Item updated successfully",
    updateError: "Error while updating Item, Please try again later",
    deleteSuccess: "Item deleted successfully",
    deleteError: "Error while deleting Item, please try again later",
    listSuccess: "Item record(s) found successfully",
    listError: "Item record(s) not found, please try again later",
  },
  Item_types : {
    createSuccess: "Item_type saved successfully",
    createError: "Error while creating Item_type, Please try again later",
    updateSuccess: "Item_type updated successfully",
    updateError: "Error while updating Item_type, Please try again later",
    deleteSuccess: "Item_type deleted successfully",
    deleteError: "Error while deleting Item_type, please try again later",
    listSuccess: "Item_type record(s) found successfully",
    listError: "Item_type record(s) not found, please try again later",
  },
  inventory : {
    createSuccess: "inventory saved successfully",
    createError: "Error while creating inventory, Please try again later",
    updateSuccess: "inventory updated successfully",
    updateError: "Error while updating inventory, Please try again later",
    deleteSuccess: "inventory deleted successfully",
    deleteError: "Error while deleting inventory, please try again later",
    listSuccess: "inventory record(s) found successfully",
    listError: "inventory record(s) not found, please try again later",
  },
  unitOfMeasure : {
    createSuccess: "unitOfMeasure saved successfully",
    createError: "Error while creating unitOfMeasure, Please try again later",
    updateSuccess: "unitOfMeasure updated successfully",
    updateError: "Error while updating unitOfMeasure, Please try again later",
    deleteSuccess: "unitOfMeasure deleted successfully",
    deleteError: "Error while deleting unitOfMeasure, please try again later",
    listSuccess: "unitOfMeasure record(s) found successfully",
    listError: "unitOfMeasure record(s) not found, please try again later",
  },
  Tenant : {
    createSuccess: "Tenant saved successfully",
    createError: "Error while creating Tenant, Please try again later",
    updateSuccess: "Tenant updated successfully",
    updateError: "Error while updating Tenant, Please try again later",
    deleteSuccess: "Tenant deleted successfully",
    deleteError: "Error while deleting unitOTenantfMeasure, please try again later",
    listSuccess: "Tenant record(s) found successfully",
    listError: "Tenant record(s) not found, please try again later",
  },
  temp_mixtures : {
    createSuccess: "temp_mixtures saved successfully",
    createError: "Error while creating temp_mixtures, Please try again later",
    updateSuccess: "temp_mixtures updated successfully",
    updateError: "Error while updating temp_mixtures, Please try again later",
    deleteSuccess: "temp_mixtures deleted successfully",
    deleteError: "Error while deleting temp_mixtures, please try again later",
    listSuccess: "temp_mixtures record(s) found successfully",
    listError: "temp_mixtures record(s) not found, please try again later",
  },
  temp_instructions : {
    createSuccess: "temp_instructions saved successfully",
    createError: "Error while creating temp_instructions, Please try again later",
    updateSuccess: "temp_instructions updated successfully",
    updateError: "Error while updating temp_instructions, Please try again later",
    deleteSuccess: "temp_instructions deleted successfully",
    deleteError: "Error while deleting temp_instructions, please try again later",
    listSuccess: "temp_instructions record(s) found successfully",
    listError: "temp_instructions record(s) not found, please try again later",
  },
  temp_ingredients : {
    createSuccess: "temp_ingredients saved successfully",
    createError: "Error while creating temp_ingredients, Please try again later",
    updateSuccess: "temp_ingredients updated successfully",
    updateError: "Error while updating temp_ingredients, Please try again later",
    deleteSuccess: "temp_ingredients deleted successfully",
    deleteError: "Error while deleting temp_ingredients, please try again later",
    listSuccess: "temp_ingredients record(s) found successfully",
    listError: "temp_ingredients record(s) not found, please try again later",
  },
  mixtures : {
    createSuccess: "mixtures saved successfully",
    createError: "Error while creating mixtures, Please try again later",
    updateSuccess: "mixtures updated successfully",
    updateError: "Error while updating mixtures, Please try again later",
    deleteSuccess: "mixtures deleted successfully",
    deleteError: "Error while deleting mixtures, please try again later",
    listSuccess: "mixtures record(s) found successfully",
    listError: "mixtures record(s) not found, please try again later",
  },
  Instructions : {
    createSuccess: "Instructions saved successfully",
    createError: "Error while creating Instructions, Please try again later",
    updateSuccess: "Instructions updated successfully",
    updateError: "Error while updating Instructions, Please try again later",
    deleteSuccess: "Instructions deleted successfully",
    deleteError: "Error while deleting Instructions, please try again later",
    listSuccess: "Instructions record(s) found successfully",
    listError: "Instructions record(s) not found, please try again later",
  },
  Mix_tests_bubble:{
    createSuccess: "Mix_tests_bubble saved successfully",
    createError: "Error while creating Mix_tests_bubble, Please try again later",
    updateSuccess: "Mix_tests_bubble updated successfully",
    updateError: "Error while updating Mix_tests_bubble, Please try again later",
    deleteSuccess: "Mix_tests_bubble deleted successfully",
    deleteError: "Error while deleting Mix_tests_bubble, please try again later",
    listSuccess: "Mix_tests_bubble record(s) found successfully",
    listError: "Mix_tests_bubble record(s) not found, please try again later",
  },
  mix_tests_endotox:{
    createSuccess: "mix_tests_endotox saved successfully",
    createError: "Error while creating mix_tests_endotox, Please try again later",
    updateSuccess: "mix_tests_endotox updated successfully",
    updateError: "Error while updating mix_tests_endotox, Please try again later",
    deleteSuccess: "mix_tests_endotox deleted successfully",
    deleteError: "Error while deleting mix_tests_endotox, please try again later",
    listSuccess: "mix_tests_endotox record(s) found successfully",
    listError: "mix_tests_endotox record(s) not found, please try again later",
  },
  mix_tests_sterility:{
    createSuccess: "mix_tests_sterility saved successfully",
    createError: "Error while creating mix_tests_sterility, Please try again later",
    updateSuccess: "mix_tests_sterility updated successfully",
    updateError: "Error while updating mix_tests_sterility, Please try again later",
    deleteSuccess: "mix_tests_sterility deleted successfully",
    deleteError: "Error while deleting mix_tests_sterility, please try again later",
    listSuccess: "mix_tests_sterility record(s) found successfully",
    listError: "mix_tests_sterility record(s) not found, please try again later",
  },
  mix_labels_process:{
    createSuccess: "mix_labels_process saved successfully",
    createError: "Error while creating mix_labels_process, Please try again later",
    updateSuccess: "mix_labels_process updated successfully",
    updateError: "Error while updating mix_labels_process, Please try again later",
    deleteSuccess: "mix_labels_process deleted successfully",
    deleteError: "Error while deleting mix_labels_process, please try again later",
    listSuccess: "mix_labels_process record(s) found successfully",
    listError: "mix_labels_process record(s) not found, please try again later",
  },
  quote:{
    createSuccess: "quote saved successfully",
    createError: "Error while creating quote, Please try again later",
    updateSuccess: "quote updated successfully",
    updateError: "Error while updating quote, Please try again later",
    deleteSuccess: "quote deleted successfully",
    deleteError: "Error while deleting quote, please try again later",
    listSuccess: "quote record(s) found successfully",
    listError: "quote record(s) not found, please try again later",
  },
  result_type:{
    createSuccess: "result_type saved successfully",
    createError: "Error while creating result_type, Please try again later",
    updateSuccess: "result_type updated successfully",
    updateError: "Error while updating result_type, Please try again later",
    deleteSuccess: "result_type deleted successfully",
    deleteError: "Error while deleting result_type, please try again later",
    listSuccess: "result_type record(s) found successfully",
    listError: "result_type record(s) not found, please try again later",
  }
};
